version: '3.8'

services:
  # Qdrant Vector Database for semantic search
  mem0_store:
    image: qdrant/qdrant:latest
    container_name: openmemory_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL for metadata storage
  postgres:
    image: postgres:15-alpine
    container_name: openmemory_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-openmemory}
      POSTGRES_USER: ${POSTGRES_USER:-openmemory_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-openmemory_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # OpenMemory MCP API Server
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: openmemory_api
    ports:
      - "8765:8765"
    env_file:
      - .env
    environment:
      - QDRANT_HOST=mem0_store
      - POSTGRES_HOST=postgres
    volumes:
      - ./api:/usr/src/openmemory
    depends_on:
      mem0_store:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # OpenMemory UI Dashboard
  openmemory-ui:
    image: mem0/openmemory-ui:latest
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: openmemory_ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=${USER_ID}
    depends_on:
      - openmemory-mcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_storage:
    name: openmemory_qdrant_storage
  postgres_data:
    name: openmemory_postgres_data

networks:
  default:
    name: openmemory_network