# Serena MCP Server 專案配置
name: "serena-mcp-server"
description: "Serena MCP Server 部署配置"
version: "1.0.0"

# 預設語言設定為 Python（因為這是最常見的）
language: "python"

# 專案結構
structure:
  # 原始碼目錄（雖然這裡主要是配置檔案）
  source_dirs:
    - "."
  
  # 忽略的檔案和目錄模式
  ignore_patterns:
    - "*.pyc"
    - "__pycache__"
    - ".git"
    - "*.log"
    - ".serena/cache"

# 專案命令
commands:
  # 執行 Serena MCP Server
  run: "./run-serena.sh"
  
  # 測試連線
  test: "./test-connection.sh"
  
  # Docker 部署
  docker: "./run-docker.sh"

# 工具特定設定
tools:
  # 搜尋工具設定
  search:
    max_results: 50
    exclude_tests: false
  
  # 記憶體工具設定
  memory:
    auto_save: true
    namespace: "serena-mcp"

# 環境變數
environment:
  SERENA_CONTEXT: "ide-assistant"
  SERENA_LOG_LEVEL: "INFO"
  SERENA_TRANSPORT: "stdio"

# 自訂提示
prompts:
  onboarding: |
    這是 Serena MCP Server 的部署配置目錄。
    主要包含配置檔案和執行腳本。
  
  context: |
    專注於配置檔案的管理和 MCP Server 的設定。