version: '3.8'

services:
  gemini-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-mcp-server
    restart: unless-stopped
    
    environment:
      # Google API 配置
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash}
      
      # Vertex AI 配置（可選）
      - GOOGLE_GENAI_USE_VERTEXAI=${GOOGLE_GENAI_USE_VERTEXAI:-false}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION:-us-central1}
      
      # 伺服器配置
      - MCP_SERVER_MODE=${MCP_SERVER_MODE:-stdio}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    # Stdio 模式不需要端口，但保留以備 HTTP 模式使用
    ports:
      - "8080:8080"
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "docker/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 資源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

# 網路配置
networks:
  default:
    name: mcp-network
    external: true